#!/usr/bin/env bash
# Stamp a unique, traceable build identity into Config/BuildInfo.xcconfig so
# every build is distinguishable — and so we can confirm the device/sim is
# actually running the build we think it is (a keyboard extension can otherwise
# keep serving a cached old binary). Regenerated on each build; gitignored.
#
#   CURRENT_PROJECT_VERSION : git commit count — the standard monotonic build
#                             number, shown as CFBundleVersion (e.g. 0.1.0 (8)).
#   OBADH_GIT_SHA           : short commit SHA, with "-dirty" if the tree has
#                             uncommitted changes (exact source traceability).
#   OBADH_BUILD_TIME        : UTC build timestamp — the "is this the latest?"
#                             signal, unique per build even on a dirty rebuild.
#
# Applies to BOTH the app and the extension (they share these settings), so the
# two bundles always report the same version — Apple requires that match anyway.
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

count="$(git rev-list --count HEAD 2>/dev/null || echo 0)"
sha="$(git rev-parse --short=8 HEAD 2>/dev/null || echo nogit)"
if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
  sha="${sha}-dirty"
fi
build_time="$(date -u +%Y-%m-%d.%H%M)"

cat > "$ROOT_DIR/Config/BuildInfo.xcconfig" <<EOF
// AUTO-GENERATED by scripts/stamp-build.sh — do not edit or commit.
CURRENT_PROJECT_VERSION = ${count}
OBADH_GIT_SHA = ${sha}
OBADH_BUILD_TIME = ${build_time}
EOF
marketing_version="$(awk '/MARKETING_VERSION:/ { gsub(/"/, "", $2); print $2; exit }' project.yml)"
echo "stamped build: ${marketing_version} (${count}) · ${sha} · ${build_time}"
